### ISSUE TITLE
Annoying Box

### ISSUE THREAD

**Issue by ungentilgarcon** [topogram/topogram#136] opened 2016-11-26 20:02 UTC
Difficult to get beyond this box:

     Click to add a title
    Group Add a group 0
    Weight 0
    Notes

0 comments navigation 

Needs to be defocused

**Comment by ungentilgarcon** [comment] 2016-12-09 15:46
Really, it ruins it all 👎

**Comment by clemsos** [comment] 2016-12-09 17:12
add /view at the end of the URL

**Comment by clemsos** [comment] 2017-10-01 14:53
duplicate of #140

**Closed as completed by clemsos** 2017-10-01 14:53 UTC
Labels: bug, important
